missing: use PTRDIFF_MAX instead of -1
On musl-gcc the compiler complains that the size passed to
memchr (-1) is larger than the object size (size_t). Looking
at the values its limiting size_t to a max size of a signed
integer (0x7FFF....) and we are passing 0xFFFFF....

Since this size is quite large its not expected that anyone
will ever need to use memchr with a buffer this big.
Limiting the size to a signed integer max value should be just
fine.

Instead, use PTRDIFF_MAX rather than -1. Below is the warning
produced in upstream:

In file included from ell/pem.c:45:
In function 'rawmemchr',
    inlined from 'pem_load_buffer' at ell/pem.c:227:21:
ell/missing.h:76:16: error: 'memchr' specified bound
	18446744073709551615 may exceed maximum object size
	9223372036854775807 [-Werror=stringop-overread]
   76 |         return memchr(s, c, (size_t) -1);